name: merging_builder

description:
  Generic builder that reads several input
  files and writes merged output to a stand-alone file.
  The builder uses synthetic input.

version: 0.1.3

homepage: https://github.com/simphotonics/merging_builder

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: ^0.39.13
  build: ^1.3.0
  dart_style: ^1.3.6
  directed_graph: ^0.1.6
  exception_templates: ^0.0.3
  glob: ^1.2.0
  meta: ^1.2.2
  path: ^1.7.0
  source_gen: ^0.9.5
  quote_buffer: ^0.1.3
  lazy_evaluation: ^0.0.6+3
dependency_overrides:
  #analyzer: 0.39.11

dev_dependencies:
  build_runner: ^1.10.0
  build_test: ^1.2.0
  pedantic: ^1.9.2
  test: ^1.15.3
