targets:
  $default:
    builders:
      # Configure the builder `pkg_name|builder_name`
      researcher_builder|add_names_builder:
        # Only run this builder on the specified input.
        enabled: true
        # generate_for:
        #   - lib/*.dart
        options:
          input_files: 'lib/input/*.dart'
          output_file: 'lib/researchers.dart'
          sort_assets: true
          header: '// Header specified in build.yaml.'
          footer: '// Footer specified in build.yaml.'
      researcher_builder|assistant_builder:
        enabled: true
