name: researcher
description:
  Example demonstrating how to use the library merging_builder.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  
dev_dependencies:
  build_runner: ^1.10.0
  researcher_builder:
    path: ../researcher_builder
