name: researcher
description: Example demonstrating how to use the library merging_builder.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: null

dev_dependencies:
  researcher_builder:
    path: ../researcher_builder
  build_runner: ^1.12.2
  build_test: ^2.0.0
  source_gen: ^0.9.10+4
  test: ^1.16.8

dependency_overrides:
  source_gen:
    git:
      url: git@github.com:dart-lang/source_gen.git
      ref: master
      path: source_gen
