builders:
  add_names_builder:
    import: "package:researcher_builder/builder.dart"
    builder_factories: ["addNamesBuilder"]
    build_extensions: {"$lib$": ["*.dart"]}
    auto_apply: root_package
    build_to: source